export const plans = [
  {
    name: 'Free',
    price: '$0',
    description: 'Perfect for personal projects and trying out AIReady.',
    features: [
      '1 team',
      '3 repositories',
      '10 analysis runs/month',
      '7-day data retention',
      'Full open-source CLI tools',
      'Local visualization',
      'JSON/HTML export',
    ],
    cta: 'Get Started',
    href: '/login',
    featured: false,
    available: true,
  },
  {
    name: 'Pro',
    price: '$49',
    description:
      'For individual developers serious about AI-friendly code quality.',
    features: [
      'Everything in Free, plus:',
      '10 repositories',
      'Unlimited analysis runs',
      '90-day data retention',
      'Historical trends & charts',
      '5 AI refactoring plans/month',
      'Email support',
    ],
    cta: 'Upgrade Now',
    href: '#',
    featured: true,
    available: true,
  },
  {
    name: 'Team',
    price: '$99',
    description:
      'Avoid the procurement nightmare while getting enterprise-grade protection.',
    features: [
      'Everything in Pro, plus:',
      'Unlimited repositories',
      'Unlimited team members',
      'Team benchmarking',
      '20 AI refactoring plans/month',
      'CI/CD integration',
      'PR Gatekeeper Mode',
      'Priority email support',
    ],
    cta: 'Upgrade Now',
    href: '#',
    featured: false,
    available: true,
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    description: 'Large organizations with strategic AI adoption programs.',
    features: [
      'Everything in Team, plus:',
      'Unlimited teams/users',
      'Unlimited refactoring plans',
      '1-year+ data retention',
      'Custom thresholds & rules',
      'API access',
      'Dedicated account manager',
      'SLA support',
    ],
    cta: 'Contact Us',
    href: '/contact',
    featured: false,
    available: false,
  },
];
