import chalk from 'chalk';
import type { PatternType } from './detector';
import { Severity } from '@aiready/core';

/**
 * Get icon for pattern type
 */
export function getPatternIcon(type: PatternType): string {
  const icons: Record<PatternType, string> = {
    'api-handler': '🌐',
    validator: '✓',
    utility: '🔧',
    'class-method': '📦',
    component: '⚛️',
    function: 'ƒ',
    unknown: '❓',
  };
  return icons[type];
}

/**
 * Generate HTML report for pattern detection results
 */
export function generateHTMLReport(summary: any, results: any[]): string {
  return `<!DOCTYPE html>
<html>
<head>
  <title>Pattern Detection Report</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; margin: 40px; background: #f5f5f5; }
    .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    h1 { color: #333; border-bottom: 3px solid #007acc; padding-bottom: 10px; }
    .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 30px 0; }
    .stat-card { background: #f9f9f9; padding: 20px; border-radius: 6px; border-left: 4px solid #007acc; }
    .stat-value { font-size: 32px; font-weight: bold; color: #007acc; }
    .stat-label { color: #666; font-size: 14px; text-transform: uppercase; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { text-align: left; padding: 12px; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; font-weight: 600; }
    .critical { color: #d32f2f; }
    .major { color: #f57c00; }
    .minor { color: #1976d2; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🔍 Pattern Detection Report</h1>
    <p>Generated: ${new Date().toLocaleString()}</p>
    
    <div class="summary">
      <div class="stat-card">
        <div class="stat-value">${results.length}</div>
        <div class="stat-label">Files Analyzed</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${summary.totalPatterns}</div>
        <div class="stat-label">Duplicate Patterns</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${summary.totalTokenCost.toLocaleString()}</div>
        <div class="stat-label">Tokens Wasted</div>
      </div>
    </div>

    <h2>Top Duplicate Patterns</h2>
    <table>
      <thead>
        <tr>
          <th>Similarity</th>
          <th>Type</th>
          <th>Files</th>
          <th>Token Cost</th>
        </tr>
      </thead>
      <tbody>
        ${summary.topDuplicates
          .slice(0, 20)
          .map(
            (dup: any) => `
          <tr>
            <td class="${dup.similarity > 0.95 ? 'critical' : dup.similarity > 0.9 ? 'major' : 'minor'}">${Math.round(dup.similarity * 100)}%</td>
            <td>${dup.patternType}</td>
            <td>${dup.files.map((f: any) => `<code>${f.path}:${f.startLine}-${f.endLine}</code>`).join('<br>↔<br>')}</td>
            <td>${dup.tokenCost.toLocaleString()}</td>
          </tr>
        `
          )
          .join('')}
      </tbody>
    </table>
  </div>

  <div class="footer">
    <p>Generated by <strong>@aiready/pattern-detect</strong></p>
    <p>Like AIReady? <a href="https://github.com/caopengau/aiready-pattern-detect">Star us on GitHub</a></p>
    <p>Found a bug? <a href="https://github.com/caopengau/aiready-pattern-detect/issues">Report it here</a></p>
  </div>
</body>
</html>`;
}

/**
 * Helper for severity numeric value
 */
export function getSeverityValue(s: any): number {
  if (s === Severity.Critical || s === 'critical') return 4;
  if (s === Severity.Major || s === 'major') return 3;
  if (s === Severity.Minor || s === 'minor') return 2;
  if (s === Severity.Info || s === 'info') return 1;
  return 0;
}

/**
 * Get colored severity badge for console output
 */
export function getSeverityBadge(severity: Severity | string): string {
  const val = getSeverityValue(severity);
  switch (val) {
    case 4:
      return chalk.bgRed.white.bold(' CRITICAL ');
    case 3:
      return chalk.bgYellow.black.bold(' MAJOR ');
    case 2:
      return chalk.bgBlue.white.bold(' MINOR ');
    case 1:
      return chalk.bgCyan.black(' INFO ');
    default:
      return chalk.bgCyan.black(' INFO ');
  }
}
